package com.example.ui.util

object L10n {

    fun t(key: String, lang: String = "en"): String {
        val isBn = lang.equals("bn", ignoreCase = true)
        return if (isBn) {
            bengaliMap[key] ?: englishMap[key] ?: key
        } else {
            englishMap[key] ?: key
        }
    }

    private val englishMap = mapOf(
        "app_title" to "LifeMate",
        "tagline" to "Your everyday life companion",
        "home" to "Home",
        "tasks" to "Tasks",
        "money" to "Money",
        "documents" to "Documents",
        "more" to "More",
        "good_morning" to "Good Morning",
        "good_afternoon" to "Good Afternoon",
        "good_evening" to "Good Evening",
        "greeting_subtitle" to "Here is your life overview for today",
        "quick_actions" to "Quick Actions",
        "add_expense" to "+ Expense",
        "add_reminder" to "+ Reminder",
        "borrow_lend" to "+ Dharkhata",
        "add_document" to "+ Document",
        "add_item" to "+ Lost Item",
        "add_commitment" to "+ Commitment",
        "today_summary" to "Today's Summary",
        "active_tasks" to "Active Tasks",
        "spent_today" to "Spent Today",
        "pending_dues" to "To Receive",
        "commitments_due" to "Commitments",
        "upcoming_reminders" to "Upcoming Reminders",
        "no_reminders" to "No reminders for today! Relax and enjoy.",
        "write_reminder_hint" to "e.g. Tomorrow at 9 AM call Rahim...",
        "write_expense_hint" to "e.g. Tea 20, Rickshaw 80, Lunch 150...",
        "ask_ai_hint" to "Ask LifeMate AI or give command...",
        "expenses" to "Expenses",
        "dharkhata" to "Dharkhata (Borrow & Lend)",
        "i_will_receive" to "I Will Receive",
        "i_have_to_pay" to "I Have to Pay",
        "all_settled" to "All debts settled! Clean slate.",
        "mark_settled" to "Mark Returned",
        "document_vault" to "Document Vault",
        "search_docs" to "Search documents...",
        "expiry_warning" to "Expires Soon",
        "pin_prompt" to "Enter Security PIN to view vault",
        "pin_set_prompt" to "Set a 4-digit PIN for privacy",
        "lost_items" to "Lost Item Tracker",
        "search_item_hint" to "Where did I keep my passport/keys?",
        "emergency_card" to "Emergency Card",
        "safe_arrival" to "Safe Arrival Check-in",
        "student_mode" to "Student Mode",
        "ai_assistant" to "LifeMate AI Assistant",
        "settings" to "Settings & Profile",
        "language" to "Language",
        "dark_mode" to "Dark Mode",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "done" to "Done",
        "arrived_safely" to "I Arrived Safely 🎉",
        "safety_active" to "Safety Timer Active",
        "where_spending_most" to "Where am I spending the most?",
        "highest_category" to "Highest spending category"
    )

    private val bengaliMap = mapOf(
        "app_title" to "লাইফমেট",
        "tagline" to "আপনার দৈনন্দিন জীবনের বিশ্বস্ত সঙ্গী",
        "home" to "হোম",
        "tasks" to "কাজ ও রিমাইন্ডার",
        "money" to "টাকা-পয়সা",
        "documents" to "ডকুমেন্ট ভল্ট",
        "more" to "অন্যান্য",
        "good_morning" to "শুভ সকাল",
        "good_afternoon" to "শুভ দুপুর",
        "good_evening" to "শুভ সন্ধ্যা",
        "greeting_subtitle" to "আজকের দিনের সংক্ষিপ্ত বিবরণ দেখুন",
        "quick_actions" to "দ্রুত অ্যাকশন",
        "add_expense" to "+ খরচ",
        "add_reminder" to "+ রিমাইন্ডার",
        "borrow_lend" to "+ ধারখাতা",
        "add_document" to "+ ডকুমেন্ট",
        "add_item" to "+ জিনিসপত্র",
        "add_commitment" to "+ প্রতিশ্রুতি",
        "today_summary" to "আজকের সামারি",
        "active_tasks" to "বাকি কাজ",
        "spent_today" to "আজকের খরচ",
        "pending_dues" to "পাওনা টাকা",
        "commitments_due" to "প্রতিশ্রুতি",
        "upcoming_reminders" to "আসন্ন রিমাইন্ডার",
        "no_reminders" to "আজকের কোনো রিমাইন্ডার নেই! সময়টা উপভোগ করুন।",
        "write_reminder_hint" to "যেমন: কাল সকাল ৯টায় রহিমকে ফোন দাও...",
        "write_expense_hint" to "যেমন: চা ২০, রিকশা ৮০, লাঞ্চ ১৫০...",
        "ask_ai_hint" to "লাইফমেট এআইকে প্রশ্ন করুন বা নির্দেশ দিন...",
        "expenses" to "দৈনন্দিন খরচ",
        "dharkhata" to "ধারখাতা (লেনদেন হিসাব)",
        "i_will_receive" to "আমি পাবো (পাওনা)",
        "i_have_to_pay" to "আমাকে দিতে হবে (দেনা)",
        "all_settled" to "সব লেনদেন পরিশোধিত! কোনো দেনা-পাওনা নেই।",
        "mark_settled" to "ফেরত পেয়েছি/দিয়েছি",
        "document_vault" to "ডকুমেন্ট ভল্ট",
        "search_docs" to "ডকুমেন্ট খুঁজুন...",
        "expiry_warning" to "শীঘ্রই মেয়াদ শেষ",
        "pin_prompt" to "ভল্ট দেখতে ৪ সংখ্যার পিন দিন",
        "pin_set_prompt" to "নিরাপত্তার জন্য ৪ সংখ্যার পিন সেট করুন",
        "lost_items" to "জিনিসপত্রের সন্ধান",
        "search_item_hint" to "যেমন: পাসপোর্ট/চাবি কোথায় রেখেছি?",
        "emergency_card" to "জরুরি তথ্য কার্ড ও কিউআর",
        "safe_arrival" to "নিরাপদ পৌঁছানোর টাইমার",
        "student_mode" to "স্টুডেন্ট মোড",
        "ai_assistant" to "লাইফমেট এআই সহকারী",
        "settings" to "সেটিংস ও প্রোফাইল",
        "language" to "ভাষা (Language)",
        "dark_mode" to "ডার্ক মোড",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল",
        "delete" to "মুছুন",
        "done" to "সম্পন্ন",
        "arrived_safely" to "আমি নিরাপদে পৌঁছেছি 🎉",
        "safety_active" to "সেফটি টাইমার চলছে",
        "where_spending_most" to "আমি সবচেয়ে বেশি খরচ কোথায় করছি?",
        "highest_category" to "সর্বোচ্চ খরচের খাত"
    )
}
